# Generated by Django 3.0.7 on 2020-06-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('volume', models.IntegerField(default=0)),
                ('open', models.FloatField(blank=True, default=None, null=True)),
                ('close', models.FloatField(blank=True, default=None, null=True)),
                ('high', models.FloatField(blank=True, default=None, null=True)),
                ('low', models.FloatField(blank=True, default=None, null=True)),
                ('adj_clsoe', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
