# Generated by Django 3.0.7 on 2020-06-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceinfo',
            name='date',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
