# Generated by Django 3.0.7 on 2020-06-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_priceinfo_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priceinfo',
            old_name='adj_clsoe',
            new_name='adj_close',
        ),
    ]
