# Generated by Django 3.0.7 on 2020-06-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockticker',
            name='avg_vol_three_month',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='stockticker',
            name='book_price',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stockticker',
            name='book_sales',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stockticker',
            name='current_ratio',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stockticker',
            name='eps_ttm',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stockticker',
            name='forward_pe',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stockticker',
            name='market_cap',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stockticker',
            name='pe_ttm',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stockticker',
            name='peg_ratio',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stockticker',
            name='per_200_mva',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stockticker',
            name='per_50_mva',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stockticker',
            name='per_52_high',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stockticker',
            name='per_52_low',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stockticker',
            name='per_day_change',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stockticker',
            name='previous_close',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stockticker',
            name='profit_margin',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stockticker',
            name='sp_500',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='stockticker',
            name='target_est_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='stockticker',
            name='trend',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockticker',
            name='volume',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='stockticker',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
