# Generated by Django 3.0.7 on 2020-06-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20200618_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockticker',
            name='price_intraday',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
