# Generated by Django 3.0.7 on 2020-06-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stockticker_price_intraday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockticker',
            name='per_50_mva',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
