# Generated by Django 3.0.7 on 2020-06-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20200618_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockticker',
            name='per_200_mva',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockticker',
            name='per_52_high',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockticker',
            name='per_52_low',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockticker',
            name='per_day_change',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockticker',
            name='previous_close',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stockticker',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
