# Generated by Django 3.0.7 on 2020-06-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20200618_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockticker',
            name='target_est_year',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
