# Generated by Django 3.0.7 on 2020-06-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20200618_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockticker',
            old_name='company_ticker',
            new_name='ticker',
        ),
    ]
