# Generated by Django 3.0.7 on 2020-06-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_auto_20200620_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('market_cap', models.CharField(blank=True, max_length=10)),
                ('trend', models.IntegerField(default=0)),
                ('sp_500', models.CharField(blank=True, max_length=6)),
                ('per_day_change', models.FloatField(blank=True, default=None, null=True)),
                ('previous_close', models.FloatField(blank=True, default=None, null=True)),
                ('volume', models.IntegerField(default=0)),
                ('per_50_mva', models.FloatField(blank=True, default=None, null=True)),
                ('per_200_mva', models.FloatField(blank=True, default=None, null=True)),
                ('per_52_low', models.FloatField(blank=True, default=None, null=True)),
                ('per_52_high', models.FloatField(blank=True, default=None, null=True)),
                ('target_est_year', models.FloatField(blank=True, default=None, null=True)),
                ('eps_ttm', models.CharField(blank=True, max_length=10)),
                ('pe_ttm', models.CharField(blank=True, max_length=10)),
                ('forward_pe', models.CharField(blank=True, max_length=10)),
                ('peg_ratio', models.CharField(blank=True, max_length=10)),
                ('book_price', models.CharField(blank=True, max_length=10)),
                ('book_sales', models.CharField(blank=True, max_length=10)),
                ('profit_margin', models.CharField(blank=True, max_length=10)),
                ('current_ratio', models.CharField(blank=True, max_length=10)),
                ('avg_vol_three_month', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('price_intraday', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
