# Generated by Django 3.0.7 on 2020-06-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_searchticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchticker',
            name='vol_trend',
            field=models.IntegerField(default=0),
        ),
    ]
