# Generated by Django 3.0.7 on 2020-06-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_searchticker_vol_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockticker',
            name='vol_trend',
            field=models.IntegerField(default=0),
        ),
    ]
